#!/bin/bash

executableDir=/tmp/_C-interp_Temp
executableFile=tmpExecutable
cFile=$0".c"

#makes the directory
mkdir $executableDir

#traps signals 0 (Exit), 1 (Hangup), 2 (Interrupt) ,3 (Quit), and 15 (Terminate)
trap "/bin/rm -rf $executableDir" EXIT SIGHUP SIGINT SIGQUIT SIGTERM


#compiles the file
gcc -o $executableDir"/"$executableFile $cFile

#gets all of the args for the c program execution
for arg
do
	argString="$argString $arg" 
done


#executes file with arguments
$executableDir"/"$executableFile $argString

